# Generated by Django 4.1 on 2022-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_categories_alter_product_subcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['pk'], 'verbose_name_plural': 'sub categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg'),
        ),
    ]
